# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  deployableBranches: [dev,main,azure-pipelines]

trigger:
  branches:
    include:
    - refs/heads/main
    - refs/heads/dev
    - refs/heads/release

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Job_1
  displayName: Main
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Docker@2
    displayName: Build, Push
    inputs:
      containerRegistry: 'dr1'
      repository: stevenheinze57/django-blogger
      buildContext: ''
      tags: >-
        $(Build.SourceBranchName)

        $(Build.SourceVersion)
  - task: Bash@3
    displayName: Deploy
    condition: and(succeeded(), contains(variables.deployableBranches, variables['Build.SourceBranchName']) )
    inputs:
      targetType: inline
      script: echo ">>>>>>>>>> INSERT DEPLOYMENT STEP HERE <<<<<<<<<<"
...
