# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - refs/heads/main
    - refs/heads/dev
    - refs/heads/release

# variables:
#   # isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev*')]
#   # isRelease: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
#   # deploy: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/dev'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))]
#   - name: deploy 
#     ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}: 
#       value: 

parameters:
  - name: deployableBranches
    type: string
    values:
      - dev
      - main


resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Job_1
  displayName: Main
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Docker@2
    displayName: Build, Push
    inputs:
      containerRegistry: 'dr1'
      repository: stevenheinze57/django-blogger
      buildContext: ''
      tags: >-
        $(Build.SourceBranchName)

        $(Build.SourceVersion)
  - task: Bash@3
    displayName: Deploy
    condition: and(succeeded(), in(variables['Build.SourceBranch'], paramaters.deployableBranches) )
    inputs:
      targetType: inline
      script: echo ">>>>>>>>>> INSERT DEPLOYMENT STEP HERE <<<<<<<<<<"
...
