
trigger:
  branches:
    include:
    - refs/heads/main
    - refs/heads/dev
    - refs/heads/release

# variables:
#   isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
#   isRelease: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: Job_1
  displayName: Main
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Docker@2
    displayName: Build, Push
    inputs:
      containerRegistry: '<YOUR_AZ_CONTAINER_REGISTRY>'
      repository: stevenheinze57/django-blogger
      buildContext: ''
      tags: >-
        $(Build.SourceBranchName)

        $(Build.SourceVersion)
  - task: Bash@3
    displayName: Deploy
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/dev'), eq(variables['Build.SourceBranch'], 'refs/heads/release')))
    inputs:
      targetType: inline
      script: echo ">>>>>>>>>> INSERT DEPLOYMENT STEP HERE <<<<<<<<<<"
...
